[build]
  command = "npm run build"    # Se houver build; se não, pode ser vazio ou "echo 'Build complete'"
  publish = "atividades_pcp"           # Pasta do seu front-end

[functions]
  directory = "netlify/functions"
